import 'package:text_to_speech_demo/models/opinion.dart';

const SAMPLE_DATA = [
  // init回避のため
  Opinion(
    title: "title",
    description: "description",
    categories: "categories",
    favorite: 0,
  ),
  Opinion(
    title: "ありがとう",
    description: "ありがとうございます",
    categories: "home-screen",
    favorite: 0,
  ),
  Opinion(
    title: "すいません",
    description: "すいません",
    categories: "home-screen",
    favorite: 0,
  ),
  Opinion(
    title: "のどがかわきました",
    description: "のどが､かわきました",
    categories: "home-screen",
    favorite: 0,
  ),
  Opinion(
    title: "エアコン",
    description: "エアコンを操作してください",
    categories: "home-screen",
    favorite: 0,
  ),
  Opinion(
    title: "トイレ",
    description: "トイレに行きたいです",
    categories: "home-screen",
    favorite: 0,
  ),
  Opinion(
    title: "ぐあいがわるいです",
    description: "具合が悪いです",
    categories: "home-screen",
    favorite: 0,
  ),
  Opinion(
    title: "かみとペン",
    description: "紙とペンをとってください",
    categories: "take-hand",
    favorite: 0,
  ),
  Opinion(
    title: "めがね",
    description: "めがねをとってください",
    categories: "take-hand",
    favorite: 0,
  ),
  Opinion(
    title: "しんぶん",
    description: "新聞をとってください",
    categories: "take-hand",
    favorite: 0,
  ),
  Opinion(
    title: "クスリ",
    description: "クスリをとってください",
    categories: "take-hand",
    favorite: 0,
  ),
  Opinion(
    title: "リモコン",
    description: "リモコンをとってください",
    categories: "take-hand",
    favorite: 0,
  ),
  Opinion(
    title: "ティッシュ",
    description: "ティッシュをとってください",
    categories: "take-hand",
    favorite: 0,
  ),
  Opinion(
    title: "タオル",
    description: "タオルをとってください",
    categories: "take-hand",
    favorite: 0,
  ),
  Opinion(
    title: "マスク",
    description: "マスクをとってください",
    categories: "take-hand",
    favorite: 0,
  ),
  Opinion(
    title: "さいふ",
    description: "さいふをとってください",
    categories: "take-hand",
    favorite: 0,
  ),
  Opinion(
    title: "くつした",
    description: "くつしたをとってください",
    categories: "take-hand",
    favorite: 0,
  ),
  Opinion(
    title: "うわぎ",
    description: "うわぎをとってください",
    categories: "take-hand",
    favorite: 0,
  ),
  Opinion(
    title: "お茶",
    description: "お茶をとってください",
    categories: "hot-drink",
    favorite: 0,
  ),
  Opinion(
    title: "コーヒー",
    description: "コーヒーをとってください",
    categories: "hot-drink",
    favorite: 0,
  ),
  Opinion(
    title: "紅茶",
    description: "紅茶をとってください",
    categories: "hot-drink",
    favorite: 0,
  ),
  Opinion(
    title: "ココア",
    description: "ココアをとってください",
    categories: "hot-drink",
    favorite: 0,
  ),
  Opinion(
    title: "ホットミルク",
    description: "ホットミルクをとってください",
    categories: "hot-drink",
    favorite: 0,
  ),
  Opinion(
    title: "スープ",
    description: "スープをとってください",
    categories: "hot-drink",
    favorite: 0,
  ),
  Opinion(
    title: "水",
    description: "水をとってください",
    categories: "cold-drink",
    favorite: 0,
  ),
  Opinion(
    title: "お茶",
    description: "お茶をとってください",
    categories: "cold-drink",
    favorite: 0,
  ),
  Opinion(
    title: "アイスコーヒー",
    description: "アイスコーヒーをとってください",
    categories: "cold-drink",
    favorite: 0,
  ),
  Opinion(
    title: "ジュース",
    description: "ジュースをとってください",
    categories: "cold-drink",
    favorite: 0,
  ),
  Opinion(
    title: "牛乳",
    description: "牛乳をとってください",
    categories: "cold-drink",
    favorite: 0,
  ),
  Opinion(
    title: "お酒",
    description: "お酒をとってください",
    categories: "cold-drink",
    favorite: 0,
  ),
];
