import '../models/opinion.dart';

const List<Opinion> opinionModel = [
  // init回避のため
  Opinion(
    title: "title",
    description: "description",
    categories: "categories",
    favorite: 0,
  ),
  Opinion(
    title: "ありがとう",
    description: "ありがとうございます",
    categories: "greeting",
    favorite: 0,
  ),
  Opinion(
    title: "すいません",
    description: "すいません",
    categories: "greeting",
    favorite: 0,
  ),
  Opinion(
    title: "エアコン",
    description: "エアコンを操作してください",
    categories: "tool",
    favorite: 0,
  ),
  Opinion(
    title: "トイレ",
    description: "トイレに行きたいです",
    categories: "place",
    favorite: 0,
  ),
  Opinion(
    title: "気持ち悪いです",
    description: "気持ち悪いです",
    categories: "emotion",
    favorite: 0,
  ),
  Opinion(
    title: "紙とペン",
    description: "紙とペンをとってください",
    categories: "tool",
    favorite: 0,
  ),
  Opinion(
    title: "メガネ",
    description: "めがねをとってください",
    categories: "tool",
    favorite: 0,
  ),
  Opinion(
    title: "新聞",
    description: "新聞をとってください",
    categories: "tool",
    favorite: 0,
  ),
  Opinion(
    title: "クスリ",
    description: "クスリをとってください",
    categories: "tool",
    favorite: 0,
  ),
  Opinion(
    title: "リモコン",
    description: "リモコンをとってください",
    categories: "tool",
    favorite: 0,
  ),
  Opinion(
    title: "ティッシュ",
    description: "ティッシュをとってください",
    categories: "tool",
    favorite: 0,
  ),
  Opinion(
    title: "タオル",
    description: "タオルをとってください",
    categories: "tool",
    favorite: 0,
  ),
  Opinion(
    title: "マスク",
    description: "マスクをとってください",
    categories: "tool",
    favorite: 0,
  ),
  Opinion(
    title: "財布",
    description: "さいふをとってください",
    categories: "tool",
    favorite: 0,
  ),
  Opinion(
    title: "靴下",
    description: "くつしたをとってください",
    categories: "tool",
    favorite: 0,
  ),
  Opinion(
    title: "上着",
    description: "うわぎをとってください",
    categories: "tool",
    favorite: 0,
  ),
  Opinion(
    title: "お茶",
    description: "お茶をとってください",
    categories: "drink",
    favorite: 0,
  ),
  Opinion(
    title: "コーヒー",
    description: "コーヒーをとってください",
    categories: "drink",
    favorite: 0,
  ),
  Opinion(
    title: "紅茶",
    description: "紅茶をとってください",
    categories: "drink",
    favorite: 0,
  ),
  Opinion(
    title: "ココア",
    description: "ココアをとってください",
    categories: "drink",
    favorite: 0,
  ),
  Opinion(
    title: "ホットミルク",
    description: "ホットミルクをとってください",
    categories: "drink",
    favorite: 0,
  ),
  Opinion(
    title: "スープ",
    description: "スープをとってください",
    categories: "drink",
    favorite: 0,
  ),
  Opinion(
    title: "水",
    description: "水をとってください",
    categories: "drink",
    favorite: 0,
  ),
  Opinion(
    title: "アイスコーヒー",
    description: "アイスコーヒーをとってください",
    categories: "drink",
    favorite: 0,
  ),
  Opinion(
    title: "ジュース",
    description: "ジュースをとってください",
    categories: "drink",
    favorite: 0,
  ),
  Opinion(
    title: "牛乳",
    description: "牛乳をとってください",
    categories: "drink",
    favorite: 0,
  ),
  Opinion(
    title: "お酒",
    description: "お酒をとってください",
    categories: "drink",
    favorite: 0,
  ),
  Opinion(
    title: "お風呂",
    description: "お風呂に行きたいです",
    categories: "place",
    favorite: 0,
  ),
  Opinion(
    title: "台所",
    description: "台所に行きたいです",
    categories: "place",
    favorite: 0,
  ),
  Opinion(
    title: "リビング",
    description: "リビングに行きたいです",
    categories: "place",
    favorite: 0,
  ),
  Opinion(
    title: "和室",
    description: "和室に行きたいです",
    categories: "place",
    favorite: 0,
  ),
  Opinion(
    title: "洗面所",
    description: "洗面所に行きたいです",
    categories: "place",
    favorite: 0,
  ),
  Opinion(
    title: "車",
    description: "車に乗りたいです",
    categories: "vehicle",
    favorite: 0,
  ),
  Opinion(
    title: "電車",
    description: "電車に乗りたいです",
    categories: "vehicle",
    favorite: 0,
  ),
  Opinion(
    title: "船",
    description: "船に乗りたいです",
    categories: "vehicle",
    favorite: 0,
  ),
  Opinion(
    title: "飛行機",
    description: "飛行機に乗りたいです",
    categories: "vehicle",
    favorite: 0,
  ),
  Opinion(
    title: "嬉しいです",
    description: "嬉しいです",
    categories: "emotion",
    favorite: 0,
  ),
  Opinion(
    title: "悲しいです",
    description: "悲しいです",
    categories: "emotion",
    favorite: 0,
  ),
  Opinion(
    title: "悔しいです",
    description: "悔しいです",
    categories: "emotion",
    favorite: 0,
  ),
  Opinion(
    title: "おはようございます",
    description: "おはようございます",
    categories: "greeting",
    favorite: 0,
  ),
  Opinion(
    title: "こんにちは",
    description: "こんにちは",
    categories: "greeting",
    favorite: 0,
  ),
  Opinion(
    title: "こんばんは",
    description: "こんばんは",
    categories: "greeting",
    favorite: 0,
  ),
  Opinion(
    title: "ありがとうございます",
    description: "ありがとうございます",
    categories: "greeting",
    favorite: 0,
  ),
  Opinion(
    title: "ごめんなさい",
    description: "ごめんなさい",
    categories: "greeting",
    favorite: 0,
  ),
  Opinion(
    title: "田中さん",
    description: "田中さん",
    categories: "else",
    favorite: 0,
  ),
  Opinion(
    title: "佐藤さん",
    description: "佐藤さん",
    categories: "else",
    favorite: 0,
  ),
  Opinion(
    title: "斎藤さん",
    description: "斎藤さん",
    categories: "else",
    favorite: 0,
  ),
  Opinion(
    title: "高橋さん",
    description: "高橋さん",
    categories: "else",
    favorite: 0,
  ),
  Opinion(
    title: "山田さん",
    description: "山田さん",
    categories: "else",
    favorite: 0,
  ),
];
