import 'package:text_to_speech_demo/models/opinion.dart';

const List<Opinion> SAMPLE_DATA = [
  // init回避のため
  Opinion(
    title: "title",
    description: "description",
    categories: "categories",
    favorite: 0,
  ),
  Opinion(
    title: "ありがとう",
    description: "ありがとうございます",
    categories: "greeting",
    favorite: 0,
  ),
  Opinion(
    title: "すいません",
    description: "すいません",
    categories: "greeting",
    favorite: 0,
  ),
  Opinion(
    title: "エアコン",
    description: "エアコンを操作してください",
    categories: "tool",
    favorite: 0,
  ),
  Opinion(
    title: "トイレ",
    description: "トイレに行きたいです",
    categories: "place",
    favorite: 0,
  ),
  Opinion(
    title: "気持ち悪いです",
    description: "気持ち悪いです",
    categories: "emotion",
    favorite: 0,
  ),
  Opinion(
    title: "紙とペン",
    description: "紙とペンをとってください",
    categories: "tool",
    favorite: 0,
  ),
  Opinion(
    title: "メガネ",
    description: "めがねをとってください",
    categories: "tool",
    favorite: 0,
  ),
  Opinion(
    title: "新聞",
    description: "新聞をとってください",
    categories: "tool",
    favorite: 0,
  ),
  Opinion(
    title: "クスリ",
    description: "クスリをとってください",
    categories: "tool",
    favorite: 0,
  ),
  Opinion(
    title: "リモコン",
    description: "リモコンをとってください",
    categories: "tool",
    favorite: 0,
  ),
  Opinion(
    title: "ティッシュ",
    description: "ティッシュをとってください",
    categories: "tool",
    favorite: 0,
  ),
  Opinion(
    title: "タオル",
    description: "タオルをとってください",
    categories: "tool",
    favorite: 0,
  ),
  Opinion(
    title: "マスク",
    description: "マスクをとってください",
    categories: "tool",
    favorite: 0,
  ),
  Opinion(
    title: "財布",
    description: "さいふをとってください",
    categories: "tool",
    favorite: 0,
  ),
  Opinion(
    title: "靴下",
    description: "くつしたをとってください",
    categories: "tool",
    favorite: 0,
  ),
  Opinion(
    title: "上着",
    description: "うわぎをとってください",
    categories: "tool",
    favorite: 0,
  ),
  Opinion(
    title: "お茶",
    description: "お茶をとってください",
    categories: "drink",
    favorite: 0,
  ),
  Opinion(
    title: "コーヒー",
    description: "コーヒーをとってください",
    categories: "drink",
    favorite: 0,
  ),
  Opinion(
    title: "紅茶",
    description: "紅茶をとってください",
    categories: "drink",
    favorite: 0,
  ),
  Opinion(
    title: "ココア",
    description: "ココアをとってください",
    categories: "drink",
    favorite: 0,
  ),
  Opinion(
    title: "ホットミルク",
    description: "ホットミルクをとってください",
    categories: "drink",
    favorite: 0,
  ),
  Opinion(
    title: "スープ",
    description: "スープをとってください",
    categories: "drink",
    favorite: 0,
  ),
  Opinion(
    title: "水",
    description: "水をとってください",
    categories: "drink",
    favorite: 0,
  ),
  Opinion(
    title: "アイスコーヒー",
    description: "アイスコーヒーをとってください",
    categories: "drink",
    favorite: 0,
  ),
  Opinion(
    title: "ジュース",
    description: "ジュースをとってください",
    categories: "drink",
    favorite: 0,
  ),
  Opinion(
    title: "牛乳",
    description: "牛乳をとってください",
    categories: "drink",
    favorite: 0,
  ),
  Opinion(
    title: "お酒",
    description: "お酒をとってください",
    categories: "drink",
    favorite: 0,
  ),
];
